# -- mode: ruby -- 
# vi: set ft=ruby :
Vagrant.configure("2") do |config|  
  config.vm.box = "bento/ubuntu-20.04"
  config.disksize.size = '100GB'
  config.vm.provider :virtualbox do |v|                                                                
    v.customize ["modifyvm", :id, "--memory", "20480"] 
    v.customize ["modifyvm", :id, "--cpus", "8"]
  end                                                                                                   
  
  config.vm.provision "A", type: "shell", path: "sigl_setup.sh"
end
