import json
import sys
import random
from gensim.models import Word2Vec
from gensim.models import KeyedVectors

with open("onedrive-test.json") as line:
    graph = json.load(line)


def generatePairs():
    pair = dict()
    for i in graph:
        if "id" in i:
            if i['type'] == "Artifact":
                pair[i['id']] = i['annotations']['path']
            if i['type'] == "Process":
                pair[i['id']] = i['annotations']['exe']
        else:
            break
    return pair


nodes = generatePairs()

# def getSum(path):
#     components = splitComponents(path)
#     total = 0
#     sumList = []
#     for i in components:
#         #this line will be replaced by the vector generated by word2vec
#         sumList.append(random.random())
#     print(sumList)    
#     total = sum(sumList)/len(components)
#     return total



def splitComponents(pathName):
    componentList = pathName.split("/")
    componentList.pop(0)
    return componentList


# print(getSum('/usr/bin/python'))\

print(nodes)

wv = KeyedVectors.load("word2vec.wordvectors", mmap='r')


print(wv['usr'])